server:
  servlet:
    contextPath: /FUNDS_TRANSFER_API
  port: 8025
kai:
  name: FUNDS_TRANSFER_API
  key: fundstransferh04ng14md3ptr4iv4ilu0n
  threadName: FUNDS_TRANSFER_API
  pollSize: 100
  error:
    code996: "Error insert request to DB#{0}"
    code997: "Cannot be processed"
    code998: "Timeout {0}"
    code999: "Internal Server Error {0}"
    code801: "Request type not valid"
    code802: "Problem with calculating timeout or sendtime in request type 'response'"
    code803: "RequestId not exist"
    code804: "Request lacks valid information: {0}"
    code805: "Problem with command in request type 'request'"
    code700: "API key not exists"
    code701: "API not exist"
    code600: "Problem in mapper object"
    code501: "Failed to insert to the database#{0}"
    code502: "Failed to update to the database#{0}"
    code503: "Failed to read from the database#{0}"
    code504: "Failed to delete from the database#{0}"
    code505: "Failed to call api#{0}"
    code333: "Don't have method validate for AuthenType"

spring:
  application:
    name: KAIASIA_FUNDS_TRANSFER
  config:
    import: optional:file:application.yml
  database:
    postgres: true
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.225.254.212:5432/KAI_API?currentSchema=fund_transfer_api
    username: fundtransfer_api
    password: fundtransfer_api@2024
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://14.225.254.212:8761/eureka

dbinfo:
  apiRequest: request_in
  apiResponse: request_out
  transactionInfo: transaction_info
dep-api:
  auth-api:
    apiName: AUTH_API
    url: http://localhost:8059/AUTH_API/process
    timeout: 60000
    apiKey: authq51klfoni1ezxl5f2ckpfx248
  t24utilsApi:
    apiName: T24_UTIL_API
    url: http://14.225.254.212:8082/T24_UTIL_API/process
    timeout: 60000
    apiKey: VDI0X1VUSUxfQVBJ
  napasApi:
    apiName: NAPAS_API
    url: http://localhost:8025/NAPAS_API/process
    timeout: 60000
    apiKey: napas861klfoni1ezxl5f2ck771